coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 5%
        base: auto
        paths:
          - "!dlrover/python/tests/"
          - "!dlrover/trainer/tests/"
       # advanced settings
        branches:
          - master
        if_ci_failed: error  #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        # basic
        target: 80%
        threshold: 5%
        base: auto
        paths:
          - "!dlrover/python/tests/"
          - "!dlrover/trainer/tests/"
       # advanced settings
        branches:
          - master
        if_ci_failed: error  #success, failure, error, ignore
        informational: false
        only_pulls: false
