---
name: inferenceoperator-test
description: run gotest to execute go test cases of ElasticJob inferenceoperator
runs:
  using: 'docker'
  image: "easydl/dlrover:ci"
  args:
    - "/bin/bash"
    - "-c"
    - "cd dlrover/go/inferenceoperator && go test ./..."
