---
name: build and publish dlrover dev image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_info: [
          { dockerfile: "./docker/ci_py38.dockerfile", image_name: "dlrover/dev_py38", platform: "linux/amd64" },
          { dockerfile: "./docker/ci_py38.dockerfile.arm64", image_name: "dlrover/dev_py38_arm64", platform: "linux/arm64" },
          { dockerfile: "./docker/ci_py310.dockerfile", image_name: "dlrover/dev_py310", platform: "linux/amd64" },
        ]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.build_info.image_name }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ${{ matrix.build_info.dockerfile }}
          platforms: ${{ matrix.build_info.platform }}
          push: true
          tags: ${{ matrix.build_info.image_name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
