---
name: main test for the project

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "examples/**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/pre-commit
  dlrover-python-test:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: checkout branch
        uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - name: RUN pytest
        uses: ./.github/actions/dlrover-python-test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: cc7fe34d-d0c2-4aa5-8692-e4c6b2b3e331
          slug: intelligent-machine-learning/dlrover
  operator-test:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - name: RUN gotest
        uses: ./.github/actions/operator-test
  brain-test:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/brain-test
  dlrover-system-test-criteo-deeprec:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/dlrover-system-test-criteo-deeprec
  dlrover-system-test-deepfm:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/dlrover-system-test-deepfm
  dlrover-system-test-tf2:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/dlrover-system-test-tf2
